# config.yaml

project:
  name: isic_skin_lesion
  seed: 1

dataset:
  name: isic2019
  path: salviohexia/isic-2019-skin-lesion-images-for-classification

model_name: resnet18

loss_function: WeightedCrossEntropy

optimizer: AdamW
optim_params:
  lr: 0.001

selection_method: Uniform
metabatch_size: 320
batch_ratio: 0.1

total_epochs: 100
diagnostics_interval: log_interval
num_workers: 8

wandb:
  project: ISIC_Initial_Runs
  name: "imbalanced_Uniform_AdamW_lr-0.001_seed1"
  
